// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";

/**
 * TojiboxReportReceipt
 * ---------------------
 * ERC-721 receipt NFT minted for every Tojibox due-diligence report
 * generated by the oracle API. Deployed on GIWA (OP-Stack EVM L2).
 *
 * Replaces the pair of Hedera-specific writes the ZoneProof original made
 * per report — an HCS audit-log entry plus a separate HTS NFT mint, both
 * via a Node sidecar wrapping the Hedera SDK — with a single on-chain
 * write. Minting this NFT both proves the report was issued by the
 * authorised oracle AND durably stores the report metadata in contract
 * state, so GET /verify/{report_hash} keeps working even after the API's
 * in-memory registry is wiped by a restart (a known limitation of the
 * original that this fixes for free, since minting a receipt was already
 * happening on every report).
 *
 * Trust model mirrors tojibox-scraper's TojiboxOracle.sol (ported from
 * RezoningOracle.sol): only the `oracle` address (or the deployer/owner)
 * may mint.
 */
contract TojiboxReportReceipt is ERC721 {

    // ── Data structures ────────────────────────────────────────────────────

    struct Report {
        bytes32 reportHash;
        string  pin;
        address oracleAddress;
        string  generatedAt;
    }

    // ── Storage ────────────────────────────────────────────────────────────

    mapping(bytes32 => Report)  public reports;          // keyed by reportHash
    mapping(bytes32 => uint256) public reportToTokenId;   // reportHash -> tokenId
    uint256                     public nextTokenId;

    address public oracle;   // authorised minter (oracle API's EOA)
    address public owner;

    // ── Events ─────────────────────────────────────────────────────────────

    event ReportMinted(uint256 indexed tokenId, bytes32 indexed reportHash, string pin);
    event OracleUpdated(address indexed previous, address indexed next);

    // ── Constructor ────────────────────────────────────────────────────────

    constructor(address _oracle) ERC721("Tojibox Report Receipt", "TOJIBOX") {
        owner  = msg.sender;
        oracle = _oracle;
    }

    // ── Modifiers ──────────────────────────────────────────────────────────

    modifier onlyOracle() {
        require(
            msg.sender == oracle || msg.sender == owner,
            "TojiboxReportReceipt: caller is not the oracle"
        );
        _;
    }

    modifier onlyOwner() {
        require(msg.sender == owner, "TojiboxReportReceipt: caller is not the owner");
        _;
    }

    // ── Write ─────────────────────────────────────────────────────────────

    /**
     * @notice Mint a receipt NFT for a generated report, storing its
     *         metadata on-chain.
     *
     * @param to           recipient of the NFT (the oracle's own address,
     *                     passed explicitly from routes/parcels.py)
     * @param reportHash   sha256 hash of the canonical report payload,
     *                     computed off-chain (see routes/parcels.py::_sign_report)
     * @param pin          Wake County parcel PIN the report covers
     * @param generatedAt  ISO-8601 timestamp the report was generated at
     *
     * @return tokenId  The ID assigned to the minted NFT (starts at 0)
     */
    function mintReceipt(
        address to,
        bytes32 reportHash,
        string calldata pin,
        string calldata generatedAt
    ) external onlyOracle returns (uint256 tokenId) {
        require(reportHash != bytes32(0), "TojiboxReportReceipt: zero report hash");
        require(reports[reportHash].reportHash == bytes32(0), "TojiboxReportReceipt: report already minted");

        tokenId = nextTokenId;
        unchecked { nextTokenId++; }

        reports[reportHash] = Report({
            reportHash:    reportHash,
            pin:           pin,
            oracleAddress: to,
            generatedAt:   generatedAt
        });
        reportToTokenId[reportHash] = tokenId;

        _safeMint(to, tokenId);

        emit ReportMinted(tokenId, reportHash, pin);
    }

    // ── Admin ─────────────────────────────────────────────────────────────

    /**
     * @notice Rotate the authorised oracle address.
     */
    function setOracle(address _oracle) external onlyOwner {
        emit OracleUpdated(oracle, _oracle);
        oracle = _oracle;
    }

    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "TojiboxReportReceipt: zero address");
        owner = newOwner;
    }
}
